# Generated by Django 5.0.7 on 2024-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='product_name',
            new_name='intro_title1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='name',
            new_name='name_Promotions',
        ),
        migrations.AddField(
            model_name='banner',
            name='intro_title2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
