# Generated by Django 5.0.7 on 2024-08-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_product_name_banner_intro_title1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='dis_price',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='price',
            new_name='old_price',
        ),
    ]
