# Generated by Django 5.0.7 on 2024-08-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_dis_price_banner_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='new_price_sub',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
    ]
